name: raumprognose
version: "1.0.0"
config-version: 2

profile: raumprognose

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  raumprognose:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
