nutzungsarten:
  - name: "Pool Vortragsräume"
    column_name: "Vortrag"
    color: "#234b60"
  - name: "Lern & Zusammenarbeitsräume"
    column_name: "Lernen"
    color: "#af2832"
  - name: "Lernarbeitsplätze Fokus & Kollaboration"
    column_name: "LAP F&K"
    color: "#dfa02d"
  - name: "Lernarbeitsplätze Meetingplaces"
    column_name: "LAP M"
    color: "#a6741a"
  - name: "Sport"
    column_name: "Sport"
    color: "#58768c"
  - name: "Bibliothek"
    column_name: "Bibliothek"
    color: "#58768c"
  - name: "Gastro"
    column_name: "Gastro"
    color: "#5f915f"
  - name: "Spezialräume"
    column_name: "Spezialräume"
    color: "#7f7f7f"
  - name: "Vereine - Initiativen"
    column_name: "Vereine Initiativen"
    color: "#d36821"
  - name: "Büro"
    column_name: "Büro"
    color: "#8f45c7"